### ISSUE TITLE
The deployed version of this code is ES6.

### ISSUE THREAD

**Issue by sorahn** [jxnblk/ruled#1]
Hey Brent,

The new version of Reflexbox that comes with this code now has a problem when building.  Babel doesn't transpile anything in the node_modules directory, and the distributed version of this code is in ES6.

What happened to us is that we ended up with ES6 code in the build, then uglify choked trying to minify it down.

We're going to back the version of reflexbox down, but If you could just update this with an ES5'd deploy, that would be super awesome!

Thanks.

**Comment by jxnblk** [comment]
Oof! Thanks! Totally missed that

**Comment by jxnblk** [comment]
Published a patch, let me know if you're still seeing issues with Reflexbox

**Comment by sorahn** [comment]
Everything back to normal. Thanks so much!
